# Site settings
title: Design Notes by Rasagy
email: hello@rasagy.in
author: Rasagy Sharma
description: "My design blog!"
baseurl: "/blog"
url: "http://rasagy.in/blog"
google_analytics:
animated: true
show_related_posts: false

# Build settings
markdown: kramdown
permalink: "/:year/:month/:title/"
paginate: 3
sass:
  compressed: true
