# Site settings
title: Design Notes by Rasagy
email: hello@rasagy.in
author: Rasagy Sharma
description: "My design blog!"
baseurl: "/blog"
url: "http://rasagy.in/blog"
google_analytics: "UA-6381820-2"
animated: true
show_related_posts: false
show_twitter_plug: false
show_disqus: true

# Social Links
github_username: "rasagy"
twitter_username: "rasagy"

# Build settings
markdown: kramdown
permalink: "/:year/:month/:title/"
paginate: 3
sass:
  compressed: true